### ISSUE TITLE
website reorganization

### ISSUE THREAD

**Issue by yunghsianglu** [PurdueCAM2Project/HELPSweb#12]
Please rename the repository to HELPSweb (or something similar)

https://www.purduehelps.org/ should have the following top-level tabs:

* About (People should be under About)
* Projects
* Publications
* Join Us
* Current Members 

Need to move most content from https://engineering.purdue.edu/HELPS
I will write the items under each in another issue

**Comment by anivegesana** [comment]
I thought we were moving the contents from HELPSweb to cam2project.net. Are we doing it from cam2project.net over HELPSweb, instead?

I finished the conversion of cam2project.net over to Hyde. Are we making a different repository for that, removing the old cam2project.net site, or moving everything to HELPSweb?

We can then add the missing content onto the site that we choose to move forward with.
